#include"stm32f10x.h"
#include"sys.h"
#include"delay.h"
#include"usart.h"
#include"led.h"
#include"touch_key.h"
#define LOAD1 50
#define LOAD2 10

int main(void){
    u8 flag=0;
    RCC_Configuration();
    LED_Init();
    TK_Init();
    USART1_Init(115200);
    while(1){
        u8 val1,val2,val3,val4;
        val1=0;
        val2=0;
        val3=0;
        val4=0;
        //A键
        while(!GPIO_ReadInputDataBit(TKPORT,TK1)){
            while((!(GPIO_ReadInputDataBit(TKPORT,TK1)))&&((val1++)<LOAD1)){
                if(!GPIO_ReadInputDataBit(TKPORT,TK2))val3++;
                delay_ms(20);
            }
            if((!GPIO_ReadInputDataBit(TKPORT,TK2))&&val3>0&&val1<LOAD1){
                printf("A向右划//%d\r\n",val3);
                flag=1;
                // while(!GPIO_ReadInputDataBit(TKPORT,TK2));
            }
            else{
                if(!flag){
                    if(val1>=LOAD1){
                        //长按
                        printf("A长按//\r\n");
                        while(!GPIO_ReadInputDataBit(TKPORT,TK1));
                    }
                    else{
                        while(GPIO_ReadInputDataBit(TKPORT,TK1)&&((val2++)<LOAD2))delay_ms(20);
                        if(val2>=LOAD2){
                            //单击
                            printf("A单击//\r\n");
                            while(!GPIO_ReadInputDataBit(TKPORT,TK1));
                        }
                        else{
                            //双击
                            printf("A双击//\r\n");
                            while(!GPIO_ReadInputDataBit(TKPORT,TK1));
                        }
                    } 
                }
                else{
                    flag=0;
                    while(!GPIO_ReadInputDataBit(TKPORT,TK1));
                }
            }       
        }
        val1=val2=val3=val4=0;
        //B键
        while(!GPIO_ReadInputDataBit(TKPORT,TK2)){
            while((!(GPIO_ReadInputDataBit(TKPORT,TK2)))&&((val1++)<LOAD1)){
                if(!GPIO_ReadInputDataBit(TKPORT,TK1))val3++;
                if(!GPIO_ReadInputDataBit(TKPORT,TK3))val4++;
                delay_ms(20);
            }
            if((!GPIO_ReadInputDataBit(TKPORT,TK1))&&val3>0&&val1<LOAD1){
                printf("B向左划//%d\r\n",val3);
                flag=1;
                //while(!GPIO_ReadInputDataBit(TKPORT,TK1));
            }
            else if((!GPIO_ReadInputDataBit(TKPORT,TK3))&&val4>0&&val1<LOAD1){
                printf("B向右划//%d\r\n",val4);
                flag=1;
                //while(!GPIO_ReadInputDataBit(TKPORT,TK3));
            }
            else{
                if(!flag){
                    if(val1>=LOAD1){
                        //长按
                        printf("B长按//\r\n");
                        while(!GPIO_ReadInputDataBit(TKPORT,TK2));
                    }
                    else{
                        while(GPIO_ReadInputDataBit(TKPORT,TK2)&&((val2++)<LOAD2))delay_ms(20);
                        if(val2>=LOAD2){
                            //单击
                            printf("B单击//\r\n");
                            while(!GPIO_ReadInputDataBit(TKPORT,TK2));
                        }
                        else{
                            //双击
                            printf("B双击//\r\n");
                            while(!GPIO_ReadInputDataBit(TKPORT,TK2));
                        }
                    }
                }
                else{
                    flag=0;
                    while(!GPIO_ReadInputDataBit(TKPORT,TK2));
                }
            }
        }
        val1=val2=val3=val4=0;
        //C键
        while(!GPIO_ReadInputDataBit(TKPORT,TK3)){
            while((!(GPIO_ReadInputDataBit(TKPORT,TK3)))&&((val1++)<LOAD1)){
                if(!GPIO_ReadInputDataBit(TKPORT,TK2))val3++;
                if(!GPIO_ReadInputDataBit(TKPORT,TK4))val4++;
                delay_ms(20);
            }
            if((!GPIO_ReadInputDataBit(TKPORT,TK2))&&val3>0&&val1<LOAD1){
                printf("C向左划//%d\r\n",val3);
                flag=1;
                //while(!GPIO_ReadInputDataBit(TKPORT,TK2));
            }
            else if((!GPIO_ReadInputDataBit(TKPORT,TK4))&&val4>0&&val1<LOAD1){
                printf("C向右划//%d\r\n",val4);
                flag=1;
                //while(!GPIO_ReadInputDataBit(TKPORT,TK4));
            }
            else{
                if(!flag){
                    if(val1>=LOAD1){
                        //长按
                        printf("C长按//\r\n");
                        while(!GPIO_ReadInputDataBit(TKPORT,TK3));
                    }
                    else{
                        while(GPIO_ReadInputDataBit(TKPORT,TK3)&&((val2++)<LOAD2))delay_ms(20);
                        if(val2>=LOAD2){
                            //单击
                            printf("C单击//\r\n");
                            while(!GPIO_ReadInputDataBit(TKPORT,TK3));
                        }
                        else{
                            //双击
                            printf("C双击//\r\n");
                            while(!GPIO_ReadInputDataBit(TKPORT,TK3));
                        }
                    }
                }
                else{
                    flag=0;
                    while(!GPIO_ReadInputDataBit(TKPORT,TK3));
                }
            }
        }
        val1=val2=val3=val4=0;

        //D键
        while(!GPIO_ReadInputDataBit(TKPORT,TK4)){
            while((!(GPIO_ReadInputDataBit(TKPORT,TK4)))&&((val1++)<LOAD1)){
                if(!GPIO_ReadInputDataBit(TKPORT,TK3))val3++;
                delay_ms(20);
            }
            if((!GPIO_ReadInputDataBit(TKPORT,TK3))&&val3>0&&val1<LOAD1){
                printf("D向右划//%d\r\n",val3);
                flag=1;
                //while(!GPIO_ReadInputDataBit(TKPORT,TK3));
            }
            else{
                if(!flag){
                    if(val1>=LOAD1){
                        //长按
                        printf("D长按//\r\n");
                        while(!GPIO_ReadInputDataBit(TKPORT,TK4));
                    }
                    else{
                        while(GPIO_ReadInputDataBit(TKPORT,TK4)&&((val2++)<LOAD2))delay_ms(20);
                        if(val2>=LOAD2){
                            //单击
                            printf("D单击//\r\n");
                            while(!GPIO_ReadInputDataBit(TKPORT,TK4));
                        }
                        else{
                            //双击
                            printf("D双击//\r\n");
                            while(!GPIO_ReadInputDataBit(TKPORT,TK4));
                        }
                    }
                }
                else{
                    flag=0;
                    while(!GPIO_ReadInputDataBit(TKPORT,TK4));
                }
            }
        }
    }
}
